steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg', 'git_short_sha=$SHORT_SHA',
    '--file', 'Dockerfile',
    '-t', 'gcr.io/luabase/lua-dbt', '.'
  ]

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c',
    'docker run --env=CH_PASSWORD=$$CH_ADMIN_PASSWORD gcr.io/luabase/lua-dbt dbt run --profiles-dir=/ --profile luabase'
  ]
  secretEnv: ['CH_ADMIN_PASSWORD']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
    '-c', 'docker run -w "/" --env=CH_ADMIN_PASSWORD=$$CH_ADMIN_PASSWORD --env=SUPABASE_SQLALCHEMY_DATABASE_URI=$$SUPABASE_SQLALCHEMY_DATABASE_URI gcr.io/luabase/lua-dbt:latest python /updateLuaSchema.py'
  ]
  secretEnv: ['CH_ADMIN_PASSWORD', 'SUPABASE_SQLALCHEMY_DATABASE_URI']

availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_ID/secrets/CH_ADMIN_PASSWORD/versions/latest'
    env: 'CH_ADMIN_PASSWORD'
  - versionName: 'projects/$PROJECT_ID/secrets/SUPABASE_SQLALCHEMY_DATABASE_URI/versions/latest'
    env: 'SUPABASE_SQLALCHEMY_DATABASE_URI'

images:
- gcr.io/luabase/lua-dbt
