steps:

- name: 'gcr.io/$PROJECT_ID/lua-dbt'
  args: ['run_dbt_and_update']
  secretEnv: ['CH_ADMIN_PASSWORD', 'SUPABASE_SQLALCHEMY_DATABASE_URI']

availableSecrets:
  secretManager:
  - versionName: 'projects/$PROJECT_ID/secrets/CH_ADMIN_PASSWORD/versions/latest'
    env: 'CH_ADMIN_PASSWORD'
  - versionName: 'projects/$PROJECT_ID/secrets/SUPABASE_SQLALCHEMY_DATABASE_URI/versions/latest'
    env: 'SUPABASE_SQLALCHEMY_DATABASE_URI'
