name: 'luabase'
version: '1.0.0'
config-version: 2

profile: luabase

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  maple_pool_factory_address: '0x2cd79f7f8b38b9c0d80ea6b230441841a31537ec'

seeds:
  luabase:
    +schema: "{{ 'seeds_test' if target.name == 'dev' else 'seeds' }}"

models:
  luabase:
    +post-hook: "{{ grant_select(this) }}"
    avalanche:
      +schema: "{{ 'avalanche_test' if target.name == 'dev' else 'avalanche' }}"
    bitcoin:
      +schema: "{{ 'bitcoin_test' if target.name == 'dev' else 'bitcoin' }}"
    ethereum:
      +schema: "{{ 'ethereum_test' if target.name == 'dev' else 'ethereum' }}"
    polygon:
      +schema: "{{ 'polygon_test' if target.name == 'dev' else 'polygon' }}"
    polygon_testnet:
      +schema: "{{ 'polygon_testnet_test' if target.name == 'dev' else 'polygon_testnet' }}"
    prices:
      +schema: "{{ 'prices_test' if target.name == 'dev' else 'prices' }}"
