name: "luabase"
version: "1.0.0"
config-version: 2

profile: "luabase"

model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

vars:
  grant_databases:
    - "avalanche"
    - "bitcoin"
    - "ethereum"
    - "ethereum_dapps"
    - "fantom"
    - "polygon"
    - "polygon_testnet"
    - "prices"
  grant_users:
    - "demo_user"
    - "teams_admin"

# Add databases and users above to grant full DB read-only access to the user
on-run-end:
  - "{{ grant_select_on_databases(var('grant_databases'), var('grant_users')) }}"

seeds:
  luabase:
    +schema: "{{ 'seeds_test' if target.name == 'dev' else 'seeds' }}"

# DO NOT REMOVE
# This helps both dbt docs and the dApp models render correctly
quoting:
  identifier: true

models:
  luabase:

    # Base
    avalanche:
      +schema: "{{ 'avalanche_test' if target.name == 'dev' else 'avalanche' }}"
    bitcoin:
      +schema: "{{ 'bitcoin_test' if target.name == 'dev' else 'bitcoin' }}"
    ethereum:
      +schema: "{{ 'ethereum_test' if target.name == 'dev' else 'ethereum' }}"
    polygon:
      +schema: "{{ 'polygon_test' if target.name == 'dev' else 'polygon' }}"
    polygon_testnet:
      +schema: "{{ 'polygon_testnet_test' if target.name == 'dev' else 'polygon_testnet' }}"
    fantom:
      +schema: "{{ 'fantom_test' if target.name == 'dev' else 'fantom' }}"
    prices:
      +schema: "{{ 'prices_test' if target.name == 'dev' else 'prices' }}"

    # Derived
    ethereum_dapps:
      +meta:
        show_in_app: false
      +schema: "{{ 'ethereum_dapps_test' if target.name == 'dev' else 'ethereum_dapps' }}"
