# Need to use the config below when running in Docker devcontainer
# see https://github.com/dbt-labs/dbt-core/issues/1063
config:
  send_anonymous_usage_stats: False
  use_colors: True

luabase:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CH_SCHEMA') }}"
      user: "{{ env_var('CH_USER') }}"
      password: "{{ env_var('CH_PASSWORD') }}"
      host: "{{ env_var('CH_HOST') }}"
      port: 8443
      verify: False
      secure: True
      connect_timeout: 10
