config:
  send_anonymous_usage_stats: False
  use_colors: True

luabase:
  target: dev
  outputs:
    dev:
      type: clickhouse
      threads: 8
      schema: default
      user: admin
      password: "{{ env_var('CH_ADMIN_PASSWORD') }}"
      host: lua-2.luabase.altinity.cloud
      cluster: lua-2
      port: 9440
      verify: False
      secure: True
      connect_timeout: 10
      send_receive_timeout: 600
    prod:
      type: clickhouse
      threads: 8
      schema: default
      user: admin
      password: "{{ env_var('CH_ADMIN_PASSWORD') }}"
      host: lua-2.luabase.altinity.cloud
      cluster: lua-2
      port: 9440
      verify: False
      secure: True
      connect_timeout: 10
      send_receive_timeout: 600
