config:
  send_anonymous_usage_stats: False
  use_colors: True

luabase:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      user: admin
      password: "{{ env_var('CH_ADMIN_PASSWORD') }}"
      host: "{{ env_var('CH_HOST') }}"
      port: 8443
      verify: False
      secure: True
      connect_timeout: 10
    prod:
      type: clickhouse
      schema: default
      user: admin
      password: "{{ env_var('CH_ADMIN_PASSWORD') }}"
      host: "{{ env_var('CH_HOST') }}"
      port: 8443
      verify: False
      secure: True
      connect_timeout: 10
