[tool.poetry]
name = "lua-dbt"
version = "1.0.0"
description = "Luabase dbt project"
authors = ["Luabase"]

[tool.poetry.dependencies]
python = "^3.10"
dbt-clickhouse = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
