select
    block_number,
    block_timestamp,
    block_hash,
    hash,
    nonce,
    transaction_index,
    transaction_type,
    from_address,
    to_address,
    value,
    {{ wei_to_eth('value') }} as value_eth,
    input,
    gas,
    gas_price,
    {{ wei_to_eth('gas_price') }} as gas_price_eth,
    max_fee_per_gas,
    max_priority_fee_per_gas,
    receipt_cumulative_gas_used,
    receipt_gas_used,
    receipt_effective_gas_price,
    receipt_contract_address,
    receipt_root,
    receipt_status,
    receipt_gas_used * gas_price as transaction_fee,
    receipt_gas_used * gas_price_eth as transaction_fee_eth
from {{ source('ethereum', 'transactions_raw') }}
