
version: 2

models:
  - name: eth_usd
    schema: prices
    description: "ETH to USD price"
    columns:
      - name: timestamp
        description: "Time when price was recorded in UTC in 5 minute intervals"
        meta:
          explore:
            title: "USD by day"
            sql: |
              select 
              toDate(toDateTime(t.timestamp)) as "xAxis",
              count(1) as "series_0"
              from ethereum.blocks as t 
              where timestamp > 0
              group by "xAxis"
              order by "xAxis" asc
      - name: price_low
        description: "Low price during the interval"
      - name: price_high
        description: "High price during the interval"
      - name: price_open
        description: "High price during the interval"
      - name: price_close
        description: "High price during the interval"
      - name: volume
        description: "Trade volume during the interval"
  - name: btc_usd
    schema: prices
    description: "BTC to USD price"
    columns:
      - name: timestamp
        description: "Time when price was recorded in UTC in 5 minute intervals"
      - name: price_low
        description: "Low price during the interval"
      - name: price_high
        description: "High price during the interval"
      - name: price_open
        description: "High price during the interval"
      - name: price_close
        description: "High price during the interval"
      - name: volume
        description: "Trade volume during the interval"
  - name: sol_usd
    schema: prices
    description: "SOL to USD price"
    columns:
      - name: timestamp
        description: "Time when price was recorded in UTC in 5 minute intervals"
      - name: price_low
        description: "Low price during the interval"
      - name: price_high
        description: "High price during the interval"
      - name: price_open
        description: "High price during the interval"
      - name: price_close
        description: "High price during the interval"
      - name: volume
        description: "Trade volume during the interval"