select
    block_number,
    block_hash,
    block_timestamp,
    hash,
    nonce,
    transaction_index,
    transaction_type,
    from_address,
    to_address,
    value,
    {{ wei_to_ftm('value') }} as value_ftm,
    input,
    gas,
    gas_price,
    {{ wei_to_ftm('gas_price') }} as gas_price_ftm,
    max_fee_per_gas,
    max_priority_fee_per_gas,
    receipt_cumulative_gas_used,
    receipt_gas_used,
    receipt_effective_gas_price,
    receipt_contract_address,
    receipt_status,
    receipt_gas_used * gas_price as transaction_fee,
    receipt_gas_used * gas_price_ftm as transaction_fee_ftm
from {{ source('fantom', 'transactions_raw') }}
