
version: 2

models:
  - name: bitcoin_blocks
    schema: bitcoin
    alias: blocks
    description: "Blocks are batches of transactions with a hash of the previous block in the chain."
    meta:
      url: https://developer.bitcoin.org/reference/block_chain.html
    columns:
      - name: number
        description: "The length of the blockchain (count of blocks)"
        tests:
          - unique
          - not_null
      - name: hash
        description: "A unique identifier for the block"
        tests:
          - unique
          - not_null
      - name: timestamp
        description: "The time when the block was mined"
      - name: weight
        description: "Size of block in bytes"
      - name: stripped_size
        description: "Stripped size of block in bytes"
      - name: size
        description: "Size of block in bytes"
      - name: version
        description: "Version"
      - name: merkle_root
        description: "The root hash of the Merkle tree of all the transactions in the block (32 byte string)"
      - name: miner
        description: "The address of the miner who mined the block"
      - name: nonce
        description: "The nonce used to mine the block"
      - name: bits
        description: ""
      - name: coinbase_param
        description: ""
      - name: transaction_count
        description: "Transaction count"
  - name: bitcoin_transactions
    schema: bitcoin
    alias: transactions
    description: >
      Bitcoin transactions are broadcast between peers in a serialized byte format, called raw format. 
      It is this form of a transaction which is SHA256(SHA256()) hashed to create the TXID and, 
      ultimately, the merkle root of a block containing the transaction—making the transaction 
      format part of the consensus rules.
    meta:
      url: https://developer.bitcoin.org/reference/transactions.html
    # "hash",
    # "size",
    # "virtual_size",
    # "version",
    # "lock_time",
    # "block_number",
    # "block_hash",
    # "block_timestamp",
    # "is_coinbase",
    # "transaction_index",
    # "input_count",
    # "output_count",
    # "input_value",
    # "output_value",
    # "fee"
    columns:
      - name: block_number
        description: "Block number of this transaction"
        tests:
          - not_null
      - name: block_hash
        description: "A unique identifier for the block"
        tests:
          - not_null
      - name: block_timestamp
        description: "Timestamp when block this transaction was in was mined"
      - name: transaction_index
        description: "Index of this transaction within the block"
        tests:
          - not_null
      - name: hash
        description: "With the signature hash, the transaction can be cryptographically proven that it came from the sender and submitted to the network."
        tests:
          - not_null
      - name: size
        description: "Size of transaction in bytes"
        tests:
          - not_null
      - name: virtual_size
        description: "Virtual size of transaction in bytes"
        tests:
          - not_null
      - name: version
        description: "Version"
        tests:
          - not_null
      - name: lock_time
        description: "Lock time"
        tests:
          - not_null
      - name: is_coinbase
        description: "Is this a coinbase transaction?"
        tests:
          - not_null
      - name: input_count
        description: "Number of inputs"
        tests:
          - not_null
      - name: output_count
        description: "Number of outputs"
        tests:
          - not_null
      - name: input_value
        description: "Total value of inputs"
        tests:
          - not_null
      - name: output_value
        description: "Total value of outputs"
        tests:
          - not_null
      - name: fee
        description: "Fee paid"
        tests:
          - not_null
  - name: bitcoin_transaction_inputs
    schema: bitcoin
    alias: transactions
    description: >
      Bitcoin transactions are broadcast between peers in a serialized byte format, called raw format. 
      It is this form of a transaction which is SHA256(SHA256()) hashed to create the TXID and, 
      ultimately, the merkle root of a block containing the transaction—making the transaction 
      format part of the consensus rules.
    meta:
      url: https://developer.bitcoin.org/reference/transactions.html
    # "block_number",
    # "block_hash",
    # "block_timestamp",
    # "transaction_hash",
    # "input_index",
    # "spent_transaction_hash",
    # "spent_output_index",
    # "script_asm",
    # "script_hex",
    # "sequence",
    # "required_signatures",
    # "type",
    # "addresses",
    # "value"
    columns:
      - name: block_number
        description: "Block number of this transaction"
        tests:
          - not_null
      - name: block_hash
        description: "A unique identifier for the block"
        tests:
          - not_null
      - name: block_timestamp
        description: "Timestamp when block this transaction was in was mined"
      - name: transaction_hash
        description: "A unique identifier for the transaction"
        tests:
          - not_null
      - name: input_index
        description: "Index of this input within the transaction"
        tests:
          - not_null
      - name: spent_transaction_hash
        description: "A unique identifier for the transaction this input is spending"
        tests:
          - not_null
      - name: spent_output_index
        description: "Index of the output within the transaction this input is spending"
        tests:
          - not_null
      - name: script_asm
        description: "The script in assembly"
        tests:
          - not_null
      - name: script_hex
        description: "The script in hex"
        tests:
          - not_null
      - name: sequence
        description: "The sequence number"
        tests:
          - not_null
      - name: required_signatures
        description: "The number of required signatures"
        tests:
          - not_null
      - name: type
        description: "The type of input"
        tests:
          - not_null
      - name: addresses
        description: "The addresses associated with this input"
        tests:
          - not_null
      - name: value
        description: "The value of this input"
        tests:
          - not_null
  - name: bitcoin_transaction_outputs
    schema: bitcoin
    alias: transactions
    description: >
      Bitcoin transactions are broadcast between peers in a serialized byte format, called raw format. 
      It is this form of a transaction which is SHA256(SHA256()) hashed to create the TXID and, 
      ultimately, the merkle root of a block containing the transaction—making the transaction 
      format part of the consensus rules.
    meta:
      url: https://developer.bitcoin.org/reference/transactions.html
    # "block_number",
    # "block_hash",
    # "block_timestamp",
    # "transaction_hash",
    # "output_index",
    # "script_asm",
    # "script_hex",
    # "required_signatures",
    # "type",
    # "addresses",
    # "value"
    columns:
      - name: block_number
        description: "Block number of this transaction"
        tests:
          - not_null
      - name: block_hash
        description: "A unique identifier for the block"
        tests:
          - not_null
      - name: block_timestamp
        description: "Timestamp when block this transaction was in was mined"
      - name: transaction_hash
        description: "A unique identifier for the transaction"
        tests:
          - not_null
      - name: output_index
        description: "Index of this output within the transaction"
        tests:
          - not_null
      - name: script_asm
        description: "The script in assembly"
        tests:
          - not_null
      - name: script_hex
        description: "The script in hex"
        tests:
          - not_null
      - name: required_signatures
        description: "The number of required signatures"
        tests:
          - not_null
      - name: type
        description: "The type of output"
        tests:
          - not_null
      - name: addresses
        description: "The addresses associated with this output"
        tests:
          - not_null
      - name: value
        description: "The value of this output"
        tests:
          - not_null