version: 2

models:
  - name: polygon_blocks
    config:
      alias: blocks
    description: "Blocks are batches of transactions with a hash of the previous block in the chain."
    meta:
      url: https://ethereum.org/en/developers/docs/blocks/
    columns:
      - name: number
        description: "The length of the blockchain (count of blocks)"
        tests:
          - unique
          - not_null
        meta:
          # name the clickhouse columns something that makes sense to echarts, e.g. xAxis
          explore:
            title: "Blocks"
            type: "bigNumber"
            subheader: "Mining {{past_30_days}} per day (last 30 days)"
            formats:
              past_30_days: '#,##0'
              total: '#,##0.0,,"M"'
            sql: |
              select 
              count(1) as "total",
              sum(case when b.timestamp >= subtractDays(today(), 30) then 1 else 0 end) / 30 as past_30_days,
              min("number") as "min",
              max("number") as "max"
              from polygon.blocks as b
      - name: hash
        description: "A unique identifier for the block"
        tests:
          - not_null
      - name: timestamp
        description: The timestamp when the block was mined (UTC)
        meta:
          # name the clickhouse columns something that makes sense to echarts, e.g. xAxis
          explore:
            title: "Blocks by day"
            sql: |
              select 
              toDate(toDateTime(t.timestamp)) as "xAxis",
              count(1) as "series_0"
              from polygon.blocks as t 
              where timestamp > 0
              group by "xAxis"
              order by "xAxis" asc
      - name: size
        description: "Size of block in bytes"
      - name: transaction_count
        description: "# of transactions in the block"
        meta:
          explore:
            title: "Transactions by day"
            sql: |
              select 
              toDate(toDateTime(t.timestamp)) as "xAxis",
              sum(transaction_count) as "series_0"
              from polygon.blocks as t 
              where timestamp > 0
              group by "xAxis"
              order by "xAxis" asc
      - name: transactions_root
        description: "The root hash of the Merkle tree of all the transactions in the block (32 byte string)"
      - name: miner
        description: "The address of the miner who mined the block"
      - name: nonce
        description: "The nonce used to mine the block"
      - name: uncles
        description: "The hashes of the uncles in the block"
      - name: mix_hash
        description: "a unique identifier for that block."
      - name: logs_bloom
        description: "The bloom filter for the logs in the block"
      - name: state_root
        description: "The root of the state trie at the end of the block"
      - name: difficulty
        description: "The effort required to mine the block"
      - name: total_difficulty
        description: "Cumulative difficulty of all blocks until the current block"
      - name: parent_hash
        description: "The hash of the parent (prior) block"
      - name: sha3_uncles
        description: "A sibling block of the parent block"
      - name: receipts_root
        description: "The hash of the root node of the trie that contains the receipts of all transactions listed in this block."
      - name: gas_used
        description: "The amount of gas used by the block"
        meta:
          explore:
            title: "Gas by day"
            sql: |
              select 
              toDate(toDateTime(t.timestamp)) as "xAxis",
              sum(gas_used) as "series_0"
              from polygon.blocks as t 
              where timestamp > 0
              group by "xAxis"
              order by "xAxis" asc
      - name: gas_limit
        description: "The gas limit allowed in the block"
      - name: base_fee_per_gas
        description: "The base fee for this block (see EIP-1559)"
      - name: extra_data
        description: "An optional 32-byte space to store extra data"

  - name: polygon_transactions
    config:
      alias: transactions
    description: >
      Transactions are cryptographically signed instructions from accounts. 
      An account will initiate a transaction to update the state of the Polygon network. 
      The simplest transaction is transferring Matic from one account to another.
    meta:
      url: https://ethereum.org/en/developers/docs/transactions/
      joins:
        to_domains:
          db: polygon
          table: domains
          type: left
          left_column: to_address
          sql_on: transactions.to_address = to_domains.owner
        from_domains:
          db: polygon
          table: domains
          type: left
          left_column: from_address
          sql_on: transactions.from_address = from_domains.owner
        to_tags:
          db: polygon
          table: tags
          type: left
          left_column: to_address
          sql_on: transactions.to_address = to_tags.address
        from_tags:
          db: polygon
          table: tags
          type: left
          left_column: from_address
          sql_on: transactions.from_address = from_tags.address
    columns:
      - name: block_number
        description: "Block number of this transaction"
        tests:
          - not_null
      - name: block_hash
        description: "A unique identifier for the block"
        tests:
          - not_null
      - name: block_timestamp
        description: "The timestamp when the block was mined (UTC)"
        meta:
          explore:
            title: "Transactions by day"
            sql: |
              select 
              toDate(toDateTime(t.block_timestamp)) as "xAxis",
              count(1) as "series_0"
              from polygon.transactions as t 
              where block_timestamp > 0
              group by "xAxis"
              order by "xAxis" asc
      - name: hash
        description: "With the signature hash, the transaction can be cryptographically proven that it came from the sender and submitted to the network."
        tests:
          - not_null
      - name: nonce
        description: "The nonce is used to ensure that each transaction is unique."
        tests:
          - not_null
      - name: transaction_index
        description: "Index of this transaction within the block"
        tests:
          - not_null
      - name: transaction_type
        description: "0 = Legacy, 1 = Access List, 2 = Dynamic Fee"
      - name: from_address
        description: "The identifier of the sender (in lowercase)"
        tests:
          - not_null
        meta:
          search: signature
          aliases:
            - from
            - signature
      - name: to_address
        description: "The receiving address (in lowercase)"
        meta:
          search: recipient
          aliases:
            - to
            - recipient
      - name: value
        description: "The amount to transfer from sender to recipient (in Wei, a denomination of Matic, 1 Matic = 10^18 Wei)"
        meta:
          explore:
            title: "Transacted by day"
            sql: |
              select 
              toDate(toDateTime(t.block_timestamp)) as "xAxis",
              sum("value"/1e18) as "series_0"
              from polygon.transactions as t 
              where block_timestamp > 0
              group by "xAxis"
              order by "xAxis" asc
      - name: value_matic
        description: "The amount transferred from sender to recipient (in Matic)"
      - name: input
        description: "The data sent along with the transaction"
      - name: gas
        description: "Gas refers to the unit that measures the amount of computational effort required to execute specific operations on the Polygon network."
      - name: gas_price
        description: "Gas price provided by the sender in Wei"
        meta:
          explore:
            title: "Avg gas price by day"
            sql: |
              select 
              toDate(toDateTime(t.block_timestamp)) as "xAxis",
              avg("gas_price"/1e9) as "series_0"
              from polygon.transactions as t 
              where block_timestamp > 0
              group by "xAxis"
              order by "xAxis"
      - name: gas_price_matic
        description: "Gas price provided by the sender in Matic"
      - name: max_fee_per_gas
        description: "Maximum limit user is willing to pay for their transaction to be executed."
      - name: max_priority_fee_per_gas
        description: "A fee (tip) to incentive miners to include a transaction in the block."
      - name: receipt_cumulative_gas_used
        description: "The total amount of gas used when this transaction was executed in the block"
      - name: receipt_gas_used
        description: "The amount of gas used by this specific transaction alone"
      - name: receipt_effective_gas_price
        description: |
          The actual value per gas deducted from the senders account. Replacement of gas_price after EIP-1559
          
          <a class="text-lime-200" href="https://consensys.net/blog/quorum/what-is-eip-1559-how-will-it-change-ethereum/" target="_blank">More info</a>
      - name: receipt_contract_address
        description: "The contract address created, if the transaction was a contract creation, otherwise null"
      - name: receipt_status
        description: "Either 1 (success) or 0 (failure) (post Byzantium)"
      - name: transaction_fee
        description: |
          Transaction fee (in Wei) paid by sender (`receipt_gas_used` * `gas_price`)
          
          <a class="text-lime-200" href="https://www.notion.so/luabase/The-ABCs-and-WTFs-of-Gas-and-Transaction-Fees-578ba4615cad492f9c55fa3c06084c1d" target="_blank">More info</a>
      - name: transaction_fee_matic
        description: |
          Transaction fee (in Matic) paid by sender (`receipt_gas_used` * `gas_price_matic`)
          
          <a class="text-lime-200" href="https://www.notion.so/luabase/The-ABCs-and-WTFs-of-Gas-and-Transaction-Fees-578ba4615cad492f9c55fa3c06084c1d" target="_blank">More info</a>


  - name: polygon_logs
    config:
      alias: logs
    description: >
      Logs are are a cheap way to store data on the Polygon blockchain. 
      An example is using logs to store historical data that can be rendered by a frontend.
    meta:
      url: https://web3js.readthedocs.io/en/v1.5.2/web3-eth.html#getpastlogs
    columns:
      - name: block_number
        description: "Block number of the transaction associated with this "
        tests:
          - not_null
      - name: block_timestamp
        description: The timestamp when the block was mined (UTC)
        meta:
          explore:
            title: "Logs by day"
            sql: |
              select 
              toDate(toDateTime(t.block_timestamp)) as "xAxis",
              count(1) as "series_0"
              from polygon.logs as t 
              where block_timestamp > 0
              group by "xAxis"
              order by "xAxis" asc
      - name: block_hash
        description: "A unique identifier for the block"
        tests:
          - not_null
      - name: address
        description: "Address this event originated from."
        tests:
          - not_null
      - name: data
        description: "The data containing non-indexed log parameter"
        tests:
          - not_null
      - name: topic1
        description: "Topic 1-3 contains indexed parameters of the log"
      - name: topic2
        description: "Topic 1-3 contains indexed parameters of the log"
      - name: topic3
        description: "Topic 1-3 contains indexed parameters of the log"
      - name: topic4
        description: "Topic 1-3 contains indexed parameters of the log"
      - name: log_index
        description: "Integer of the event index position in the block"
      - name: transaction_hash
        description: "Integer of the event index position in the block"
      - name: transaction_index
        description: "Index of this transaction within the block"

  - name: polygon_traces
    config:
      alias: traces
    description: >
      Traces are a way to store extra data on the Polygon blockchain.
    meta:
      url: https://geth.ethereum.org/docs/dapp/tracing
    columns:
      - name: block_number
        description: "Block number of the transaction associated with this "
        tests:
          - not_null
      - name: block_timestamp
        description: The timestamp when the block was mined (UTC)
        meta:
          explore:
            title: "Transactions by day"
            sql: |
              select 
              toDate(toDateTime(t.block_timestamp)) as "xAxis",
              count(1) as "series_0"
              from polygon.traces as t 
              where block_timestamp > 0
              group by "xAxis"
              order by "xAxis" asc
      - name: block_hash
        description: "A unique identifier for the block"
        tests:
          - not_null
      - name: transaction_hash
        description: "Integer of the event index position in the block"
      - name: transaction_index
        description: "Index of this transaction within the block"
      - name: from_address
        description: "Address this event originated from."
        tests:
          - not_null
      - name: to_address
        description: "Address this event originated from."
      - name: value
        description: "The amount of ETH to transfer from sender to recipient (in WEI, a denomination of ETH, 1 eth = 10^18 wei)"
        meta:
          explore:
            title: "Trace value by day"
            sql: |
              select 
              toDate(toDateTime(t.block_timestamp)) as "xAxis",
              sum("value"/1e18) as "series_0"
              from polygon.traces as t 
              where block_timestamp > 0
              group by "xAxis"
              order by "xAxis" asc
      - name: input
        description: "The data containing non-indexed log parameter"
      - name: trace_type
        description: "Type of trace"
      - name: trace_id
        description: "Unique identifier for this trace"
        tests:
          - not_null
      - name: call_type
        description: "Type of call"
      - name: reward_type
        description: "Type of reward"
      - name: gas
        description: "The amount of gas used by this transaction"
      - name: gas_used
        description: "The amount of gas used by this transaction"
      - name: subtraces
        description: "The number of subtraces"
      - name: trace_address
        description: "The address of this trace"
      - name: error
        description: "The error message"
      - name: status
        description: "The status of this trace"

  - name: polygon_tokens
    config:
      alias: tokens
    description: Polygon tokens
    columns:
      - name: block_number
        description: The length of the blockchain (count of blocks)
        tests:
          - not_null
      - name: block_timestamp
        description: The timestamp when the block was mined (UTC)
        tests:
          - not_null
      - name: block_hash
        description: A unique identifier for the block
        tests:
          - not_null
      - name: address
        description: Token address
        tests:
          - not_null
      - name: symbol
        description: Token symbol
      - name: decimal
        description: How divisible a token can be
      - name: total_supply
        description: Total supply of the token

  - name: polygon_contracts
    config:
      alias: contracts
    description: Polygon contracts
    columns:
      - name: block_number
        description: The length of the blockchain (count of blocks)
        tests:
          - not_null
      - name: block_timestamp
        description: The timestamp when the block was mined (UTC)
        tests:
          - not_null
      - name: block_hash
        description: A unique identifier for the block
        tests:
          - not_null
      - name: address
        description: Contract address
      - name: bytecode
        description: Contract bytecode
      - name: function_sighashes
        description: Contract function sighashes
      - name: is_erc20
        description: Whether the contract conforms to the ERC20 standard
      - name: is_erc721
        description: Whether the contract conforms to the ERC721 standard

  - name: polygon_token_transfers
    config:
      alias: token_transfers
    description: Polygon token transfers
    columns:
      - name: block_number
        description: The length of the blockchain (count of blocks)
        tests:
          - not_null
      - name: block_timestamp
        description: The timestamp when the block was mined (UTC)
        tests:
          - not_null
      - name: block_hash
        description: A unique identifier for the block
        tests:
          - not_null
      - name: transaction_hash
        description: >
          With the signature hash, the transaction can be cryptographically proven that it came from the sender 
          and submitted to the network.
        tests:
          - not_null
      - name: log_index
        description: Integer of the event index position in the block
      - name: token_address
        description: Token address
      - name: from_address
        description: The sending address
      - name: to_address
        description: The receiving address
      - name: value
        description: The amount transferred from sender to recipient
