name: CI Pipeline

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Github
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # gCloud
      - id: auth
        name: gCloud Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: gcloud info
      - name: rsync
        run: gsutil -m rsync -r -d -x '.git/|.idea/|.env|.github/|.venv/|logs/|target/|analyses/|poetry.lock' . gs://lua-dbt/dev

      # Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Pip install requests
        run: pip install requests

      # dbt
      - name: Set target as dev
        if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
        run: |
          echo "TARGET=dev" >> $GITHUB_ENV
      - name: Set target as prod
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          echo "TARGET=prod" >> $GITHUB_ENV
      - name: Run build script
        run: python .github/scripts/dbt_build.py
        env:
          TARGET: ${{ env.TARGET }}
      - name: Run sync script
        run: python .github/scripts/sync_app.py
        env:
          TARGET: ${{ env.TARGET }}
