name: CI Pipeline

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # GitHub
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      # Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Pip install requests
        run: pip install requests

      # dbt
      - name: Set target as dev
        if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
        run: |
          echo "TARGET=dev" >> $GITHUB_ENV
      - name: Set target as prod
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          echo "TARGET=prod" >> $GITHUB_ENV
      - name: Run CI build
        id: ci-build
        run: python .github/scripts/ci_build.py
        env:
          TARGET: ${{ env.TARGET }}
          GH_BRANCH: ${{ steps.branch-name.outputs.current_branch }}
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
        with:
          message: |
            ## 🏃 dbt Run Results
            
            Status: ${{ env.DBT_RUN_ICON }}
            View Run: https://lua-dbt-services-frontend-msgn5tdnsa-uc.a.run.app/?run_id=${{ env.DBT_RUN_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run sync app data
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: python .github/scripts/sync_app.py
